### ISSUE TITLE
Choose a crate for db interaction

### ISSUE THREAD

**Issue by alisomay** [rust-at-night/rust-at-night-website#11]
I have used `sea-orm` for a long time and I'm not super happy.

Generally idea of an `orm` does not feel very good anymore. 
If you do anything complex you start writing plain SQL again. 

So I'd say we check `diesel` and maybe more lower level crates `sqlx` etc.

When we decide on something we can start building on top of it.

**Comment by ozankasikci** [comment]
I can rely on your choice on this @alisomay , please lead the way :)

**Comment by alisomay** [comment]
I think https://github.com/andrewwhitehead/sqlx would suffice. 
It is simple as hell and includes all the necessary functionalities imo.
