### ISSUE TITLE
Setup migrations with Sqlx

### ISSUE THREAD

**Issue by alisomay** [rust-at-night/rust-at-night-website#17]
Some sources to get started.
https://docs.rs/sqlx/latest/sqlx/migrate/trait.MigrationSource.html

**Comment by dvtkrlbs** [comment]
When we integrate should we separate our data layer from the endpoint functions and call this layer from the endpoints or just yolo all it on the endpoints. Another consideration is should we keep the queries in files and use query_file or inline them ?
